nats.addresses = ['nats://localhost:4222']
otel.exclusions = ['/health']
elasticsearch.httpHosts = 'http://localhost:9200,http://127.0.0.2:9200'
consul.client.registration.enabled = true
hystrix.stream.enabled = false
hazelcast.network.addresses = "['121.0.0.1:5701']"
camunda.external-client.base-url = 'http://localhost:8080/engine-rest'
mongodb.uri = 'mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb'
rabbitmq.uri = 'amqp://localhost:5672'
redis.uri = 'redis://localhost'
flyway.datasources.default.enabled = true

[datasources.default]
url = 'jdbc:mariadb://localhost:3306/db'
username = 'root'
password = ''
driver-class-name = 'org.mariadb.jdbc.Driver'
db-type = 'mariadb'

[vertx.pg.client]
port = 5432
host = 'the-host'
database = 'the-db'
database.user = 'user'
database.password = 'password'
database.maxSize = 5

[micronaut.metrics.export.stackdriver]
enabled = true
projectId = '${STACKDRIVER_PROJECT_ID}'
step = 'PT1M'

[micronaut]
session.http.coherence.enabled = true
jms.sqs.enabled = true

[micronaut.metrics.export.atlas]
enabled = true
uri = 'http://localhost:7101/api/v1/publish'
step = 'PT1M'

[otel.traces]
exporter = 'jaeger,zipkin,otlp,logging'
propagator = 'tracecontext, baggage, xray'

[micronaut.metrics.export.appoptics]
enabled = true
apiToken = '${APPOPTICS_API_TOKEN}'
step = 'PT1M'

[vertx.mysql.client]
port = 3306
host = 'the-host'
database = 'the-db'
database.user = 'user'
database.password = 'password'
database.maxSize = 5

[micronaut.metrics.export.datadog]
enabled = true
apiKey = '${DATADOG_APIKEY}'
step = 'PT1M'

[console]
enabled = true
addresses = ['/127.0.0.1', '/0:0:0:0:0:0:0:1']
header-name = 'X-Console-Verify'
header-value = '88bee20d-9b6e-44e0-8543-50e8f419b7b8'

[mqtt.client]
server-uri = 'tcp://localhost:1883'
client-id = '${random.uuid}'

[micronaut.metrics.export.ganglia]
enabled = true
protocolVersion = 3.1
step = 'PT1M'

[jpa.default]
properties.hibernate.hbm2ddl.auto = 'none'
reactive = true

[jpa.default.properties.hibernate.connection]
url = '${datasources.default.url}'
username = '${datasources.default.username}'
password = '${datasources.default.password}'

[micronaut.metrics.export.elastic]
enabled = true
step = 'PT1M'

[micronaut.metrics]
export.cloudwatch.enabled = true
enabled = true

[micronaut.metrics.export.statsd]
enabled = true
flavor = 'datadog'
host = 'localhost'
port = 8125
step = 'PT1M'

[micronaut.metrics.export.newrelic]
enabled = true
apiKey = '${NEWRELIC_API_KEY}'
accountId = '${NEWRELIC_ACCOUNT_ID}'
step = 'PT1M'

[micronaut.metrics.export.kairos]
enabled = true
step = 'PT1M'

[micronaut.metrics.export.influx]
enabled = true
step = 'PT1M'

[micronaut.metrics.export.graphite]
enabled = true
host = 'localhost'
port = 2004
step = 'PT1M'

[micronaut.security]
authentication = 'session'
intercept-url-map = [{access = 'isAnonymous()', pattern = '/swagger/**'}, {access = 'isAnonymous()', pattern = '/swagger-ui/**'}]

[micronaut.jms.activemq.artemis]
enabled = true
connection-string = 'tcp://localhost:61616'

[micronaut.metrics.export.humio]
enabled = true
step = 'PT1M'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'

[micronaut.metrics.export.prometheus]
enabled = true
descriptions = true
step = 'PT1M'

[micronaut.metrics.export.dynatrace]
enabled = true
apiToken = '${DYNATRACE_DEVICE_API_TOKEN}'
uri = '${DYNATRACE_DEVICE_URI}'
deviceId = '${DYNATRACE_DEVICE_ID}'
step = 'PT1M'

[microstream.cache.my-cache]
key-type = 'java.lang.Integer'
value-type = 'java.lang.String'
